# Site settings
title: Last Crack
email: youremailaddress@gmail.com
description: THE UP RISING
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url: https://facebook.com/lastcrack
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/lastcrack
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/lastcrack

# Build settings
markdown: kramdown
